# Generated by Django 5.1.1 on 2024-10-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_alter_libros_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='tipo',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés'), ('FR', 'Francés'), ('IT', 'Italiano')], default='FR', max_length=2),
        ),
    ]
