# Generated by Django 5.1.1 on 2024-10-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_libros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Autor',
        ),
        migrations.AddField(
            model_name='libros',
            name='autores',
            field=models.ManyToManyField(to='ejemplo.autor'),
        ),
    ]
